# Generated by Django 4.0.1 on 2023-02-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('userRank', models.CharField(max_length=50, null=True)),
                ('userTelegramId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=100)),
                ('taskDescription', models.TextField(blank=True, max_length=10000, null=True)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('done', models.CharField(choices=[('Done', 'Done'), ('In Process', 'In Process'), ('Expired', 'Expired'), ('Not Started', 'Not Started'), ('Cancelled', 'Cancelled'), ('Declined', 'Declined')], default='Not Started', max_length=20)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_backend.user')),
            ],
        ),
    ]
