# Generated by Django 4.0.1 on 2023-02-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_backend', '0002_alter_task_endtime_alter_task_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='userTelegramId',
            field=models.IntegerField(unique=True),
        ),
    ]
