# Generated by Django 4.0.1 on 2023-02-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('building', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('financing', models.IntegerField()),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
