# Generated by Django 4.0.1 on 2023-02-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0002_remove_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userBallance',
            field=models.CharField(max_length=100000),
        ),
    ]
