# Generated by Django 4.0.1 on 2023-02-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGrocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=1000)),
                ('type', models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable')], max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('image_base64', models.CharField(blank=True, max_length=1000000)),
            ],
        ),
    ]
