# Generated by Django 4.0.1 on 2023-02-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0003_alter_user_userballance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userID',
            field=models.IntegerField(default=346273373),
            preserve_default=False,
        ),
    ]
