# Generated by Django 4.0.1 on 2023-02-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0005_alter_user_userballance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userBallance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=50),
        ),
    ]
