# Generated by Django 4.0.1 on 2023-02-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0006_alter_user_userballance_alter_user_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userBallance',
            new_name='Ballance',
        ),
    ]
