# Generated by Django 4.0.1 on 2023-02-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0007_rename_userballance_user_ballance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userID',
            new_name='UserID',
        ),
    ]
