# Generated by Django 4.0.1 on 2023-02-07 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0008_rename_userid_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('BuyerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_bot.user')),
                ('ProductName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_bot.product')),
            ],
        ),
    ]
